### ISSUE TITLE
Size Calculation for Cylindrical & Non-Cylindrical Models

### ISSUE THREAD

**Issue by nirusatya** [SimplifiedLogic/creoson#4]
Is there any Customization developed to calculate the size of the models?
Size for Cylindrical Models should be **ØDxH** and **LxBxH** for Non-Cylindrical Models.

**Creo Parametric** through **ModelCHECK** can only give **LxBxH**, which considers Datum elements as well.

The solution should consider only Solid Geometry and should recognize partial Cylindrical Models too like the image attached.

If the solution can **create a Parameter** that would be more grateful which **can be called into Drawings and can go into Windchill** as well.

![parial_cylindrical_models](https://user-images.githubusercontent.com/34827759/34619693-03ae1a76-f269-11e7-9959-97b229f7f7cb.jpg)

Regards,
Niranjan V

**Comment by davidhbigelow** [comment]
CREOSON -DOES- have the ability to compute the bounding box of a model (part/assembly).

HOWEVER, PTC deliberately does NOT return "accurate" values of the bounding box - go figure!

We have raised the issue to PTC, but we have not heard of any timeline for resolution.  The problem seems to come up specifically with models that are cylindrical or have cylindrical or fillet types of features associated with them.

Best advice we have is to try the CREOSON function out and see if it can work for your application/need.  The values that come back are not "prefect" -- but are often "close enough" -- if "close enough" is good for your needs, then it may be a fit.

Look at the following CREOSON command/function combination to learn more:

"command" : "geometry"
"function" : "bound_box"

![2018-01-05 at 12 19 pm](https://user-images.githubusercontent.com/1648805/34620210-ad2a5ef4-f212-11e7-9e6f-0d61f56521e2.png)
